#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InventoryMan.Resource", IsApplication=true)]

namespace InventoryMan
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::InventoryMan.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::InventoryMan.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonDiscoNo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonDiscoYes = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonLoginStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int mLogo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int SplashCentered = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070030
			public const int btnAdd = 2131165232;
			
			// aapt resource value: 0x7f070018
			public const int btnAddNew = 2131165208;
			
			// aapt resource value: 0x7f07003d
			public const int btnCreate = 2131165245;
			
			// aapt resource value: 0x7f07000c
			public const int btnCreateAcc = 2131165196;
			
			// aapt resource value: 0x7f070036
			public const int btnDisco = 2131165238;
			
			// aapt resource value: 0x7f07002f
			public const int btnHome = 2131165231;
			
			// aapt resource value: 0x7f070035
			public const int btnHomeLog = 2131165237;
			
			// aapt resource value: 0x7f070032
			public const int btnLog = 2131165234;
			
			// aapt resource value: 0x7f07003c
			public const int btnLogin = 2131165244;
			
			// aapt resource value: 0x7f070017
			public const int btnLogout = 2131165207;
			
			// aapt resource value: 0x7f07000f
			public const int btnNo = 2131165199;
			
			// aapt resource value: 0x7f070031
			public const int btnRemove = 2131165233;
			
			// aapt resource value: 0x7f070008
			public const int btnSubmit = 2131165192;
			
			// aapt resource value: 0x7f070010
			public const int btnYes = 2131165200;
			
			// aapt resource value: 0x7f07003b
			public const int editPassword = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public const int editUsername = 2131165242;
			
			// aapt resource value: 0x7f070007
			public const int edtComments = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int edtDesc = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int edtItemName = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int edtLead = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int edtLoc = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int edtPartNum = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int edtPassword = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int edtQoh = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int edtUsername = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int homeLayout = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int homeNav = 2131165206;
			
			// aapt resource value: 0x7f070039
			public const int imgSplashLogo = 2131165241;
			
			// aapt resource value: 0x7f07002c
			public const int layoutComments = 2131165228;
			
			// aapt resource value: 0x7f070020
			public const int layoutDesc = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int layoutLead = 2131165222;
			
			// aapt resource value: 0x7f070023
			public const int layoutLoc = 2131165219;
			
			// aapt resource value: 0x7f07001a
			public const int layoutName = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int layoutPart = 2131165213;
			
			// aapt resource value: 0x7f070029
			public const int layoutQoh = 2131165225;
			
			// aapt resource value: 0x7f07002d
			public const int lblComments = 2131165229;
			
			// aapt resource value: 0x7f070021
			public const int lblDesc = 2131165217;
			
			// aapt resource value: 0x7f070027
			public const int lblLead = 2131165223;
			
			// aapt resource value: 0x7f070024
			public const int lblLoc = 2131165220;
			
			// aapt resource value: 0x7f07001b
			public const int lblName = 2131165211;
			
			// aapt resource value: 0x7f07001e
			public const int lblPartNumber = 2131165214;
			
			// aapt resource value: 0x7f07002a
			public const int lblQoh = 2131165226;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070034
			public const int linearLog = 2131165236;
			
			// aapt resource value: 0x7f070038
			public const int linearLogin = 2131165240;
			
			// aapt resource value: 0x7f070015
			public const int list = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int scrollHome = 2131165201;
			
			// aapt resource value: 0x7f070033
			public const int scrollLog = 2131165235;
			
			// aapt resource value: 0x7f070037
			public const int scrollLogin = 2131165239;
			
			// aapt resource value: 0x7f070014
			public const int searchBar = 2131165204;
			
			// aapt resource value: 0x7f070009
			public const int textView1 = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int txtAddNewTitle = 2131165184;
			
			// aapt resource value: 0x7f07002e
			public const int txtComments = 2131165230;
			
			// aapt resource value: 0x7f070022
			public const int txtDesc = 2131165218;
			
			// aapt resource value: 0x7f07001c
			public const int txtItemName = 2131165212;
			
			// aapt resource value: 0x7f070019
			public const int txtItemTitle = 2131165209;
			
			// aapt resource value: 0x7f070028
			public const int txtLead = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int txtLoc = 2131165221;
			
			// aapt resource value: 0x7f07001f
			public const int txtPartNumber = 2131165215;
			
			// aapt resource value: 0x7f07000d
			public const int txtPrompt = 2131165197;
			
			// aapt resource value: 0x7f07002b
			public const int txtQoh = 2131165227;
			
			// aapt resource value: 0x7f070013
			public const int txtWelcome = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddNew = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Create = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Disco = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ItemDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ItemLog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
